# Generated by Django 5.2.5 on 2025-08-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('staff', 'Staff'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
