# Generated by Django 5.2.5 on 2025-08-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_phone_number_alter_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.TextField(null=True),
        ),
    ]
