# Generated by Django 5.2.5 on 2025-09-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_seller_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='seller/banners/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller/logos/'),
        ),
    ]
