# Generated by Django 5.2.5 on 2025-08-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'Giao hàng tiêu chuẩn (3-5 ngày)'), ('express', 'Giao hàng nhanh (1-2 ngày)'), ('pickup', 'Nhận tại cửa hàng')], default='standard', max_length=20),
        ),
    ]
