# Generated by Django 5.2.5 on 2025-08-27 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_role'),
        ('order', '0005_alter_order_shipping_cost_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.seller'),
        ),
    ]
