# Generated by Django 5.1.4 on 2025-08-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_average_rating_product_total_reviews_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
