# Generated by Django 5.1.4 on 2025-08-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
