# Generated by Django 5.2.5 on 2025-08-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
